### ISSUE TITLE
Probleme bei einzelnen Gruppen

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [geoboxag/GEOBOX.OSC.IM.DataCheckerTool#1]
Wenn man eine Struktur dieser Art exportiert, dann klappt es:
- Obertitel
     - Gruppentitel
            - Prüfung 1
            - Prüfung 2

Wenn die Struktur aber nur eine Ebene hat, dann wird nur der Gruppentitel angezeigt:
- Gruppentitel
      - Prüfung 1
      - Prüfung 2

**Comment by urss1** [comment]
Besten Dank für die Meldung.

Leider kann ich den Effekt nicht reproduzieren.

Wenn ich eine Daten-Check Datei mit nur einer Ebene (Gruppe) habe, zeigt es mir die entsprechenden Prüfungen auch an:
![2021-01-23 09_48_50-Window](https://user-images.githubusercontent.com/5768081/105573794-605ec800-5d60-11eb-9a78-2534458ecb86.png)

Die verwendete XML-Datei sieht so aus:
![2021-01-23 09_53_14-Window](https://user-images.githubusercontent.com/5768081/105573889-f135a380-5d60-11eb-9641-c509f3123ba9.png)

Ist einen Unterschied zu Deiner XML-Datei sichtbar?
Kannst Du mir sonst einmal eine XML-Datei die nicht korrekt Angezeigt wird zur Verfügung stellen?

**Comment by Pierre-de-la-Verre** [comment]
Ich habe das Problem gefunden. Die Datei hatte nur die Prüfungseinträge und keine "Parent"-Struktur. Passiert, wenn man
- eine einzelne Prüfung exportiert (ist hier sinnlos, weil eine kann man nicht sortieren)
- Gruppen unterhalb der ersten Unterebene ~~sortiert~~ exportiert- z.B. hier:- 
![grafik](https://user-images.githubusercontent.com/13277944/105700177-c6864f00-5f08-11eb-9341-c17176195097.png)
```
<?xml version="1.0" encoding="utf-8"?>
<DataChecks>
  <DataCheck ID="11" ParentDataCheckID="10" Name="Kontakte" Description="" DataCheckSqlStatement="" WithoutRLS="false" Active="true" ModuleName="" />
  <DataCheck ID="12" ParentDataCheckID="11" Name="Kontakt ohne Firma/Bezeichnung" Description="" DataCheckSqlStatement="select fid from ww_ad_contact where company is null" WithoutRLS="false" Active="true" ModuleName="" />
  <DataCheck ID="13" ParentDataCheckID="11" Name="Kontakt ohne Art" Description="" DataCheckSqlStatement="select fid from ww_ad_contact where id_contact_type is null" WithoutRLS="false" Active="true" ModuleName="" />
  <DataCheck ID="14" ParentDataCheckID="11" Name="Kontakt Hierarchie ohne Kontakt" Description="" DataCheckSqlStatement="select fid from ww_ad_contact_hierarchy where fid_contact is null" WithoutRLS="false" Active="true" ModuleName="" />
  <DataCheck ID="15" ParentDataCheckID="11" Name="Kontakt Hierarchie ohne Teil von" Description="" DataCheckSqlStatement="select fid from ww_ad_contact_hierarchy where fid_contact_from is null" WithoutRLS="false" Active="true" ModuleName="" />
  <DataCheck ID="16" ParentDataCheckID="11" Name="Mehr als ein MD Datenherr" Description="Es darf nur ein aktiver MD Datenherr in Kontakte haben" DataCheckSqlStatement="select a.fid from WW_AD_CONTACT a, WW_AD_CONTACT b&#xA;where a.fid&lt;&gt;b.fid and a.is_data_owner=1 and b.is_data_owner=1 and a.active=1 and b.active=1" WithoutRLS="false" Active="true" ModuleName="" />
</DataChecks>
```

**Comment by urss1** [comment]
Es kommt neue eine Meldung, wenn eine Datei geöffnet wird mit fehldenen übergeordneten (ParentDataCheckID) Daten-Checks.

Grundsätzlich gilt: jeweils sämtliche Datenprüfungen aus der Fachschale zur Exportieren um mit diesem Tool zu sortieren, da die ID's in der Datei umgeschrieben werden. Dies kann ansonsten beim Import zu unerwünschten Effekten führen.
