### ISSUE TITLE
Unklare Fehlermeldung bei read-only-Dateien

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [geoboxag/GEOBOX.OSC.IM.DataCheckerTool#2]
Öffnet man die gleiche Datei, einmal ohne "read-only", dann mit, dann passiert das im Log:

```
Datei wurde ausgewählt: [D:\test\schreibschutz_aus.xml]
[ERR]: Datei kann nicht gelesen werden: [Der Zugriff auf den Pfad "D:\test\schreibschutz_an.xml" wurde verweigert.]
```

Gemeint ist damit wahrscheinlich "Ich öffne eine read-only Datei gar nicht, weil ich sie ohnehin nicht speichern kann." 

Besser wäre vielleicht, sie zumindest für Betrachtungen schon zu öffnen und entweder
a) die Meldung anzupassen oder
b) eine "Speichern als .." Funktion einzubauen.

Danke:

**Comment by urss1** [comment]
Die Meldung "Der Zugriff auf den Pfad ... wurde verweigert." ist vom System und wird durch das Tool lediglich angezeigt.
Diese Meldung kann verschiedene Ursachen haben: Schreibgeschütze Dateien oder Verzeichnisse, Ungenügende Berechtigungen, ...

Solche Dateien nur Anzeigen ist nicht Aufgabe von diesem Tool.
